inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_auth_hash

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Brewfile'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
