name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - name: Start services
      run: |
        docker-compose up -d
    - name: Install PostgreSQL Client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client libpq-dev
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --without production
    - name: Setup the Database
      run: |
        bundle exec rake db:create db:migrate db:test:prepare
        bundle exec rake factory_bot:lint
    - name: Lint code with Rubocop
      run: |
        bundle exec rubocop -P
    - name: Build and test with RSpec
      run: |
        bundle exec rspec
